### PR TITLE
Add custom submodule directory functionality

### PR DESCRIPTION
**Pull request by foreignsasquatch**

### CODE REVIEW

**Comment by tobil4sk** [comment]
Did you want to make any changes before having this merged?

**Comment by foreignsasquatch** [comment]
Yeah didnt get time to do it, will improve in a few days

**Comment by tobil4sk** [comment]
I ended up adding this myself to the main branch based mostly on your PR. Thanks for your time!

**Comment by foreignsasquatch** [comment]
ah nice!

**Pull request closed without merging**
